apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    labels:
    app: quotesapi
  name: quotesapi
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: quotesapi:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: quotes
    git:
      uri: https://github.com/asolipu/DO288-apps
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: php:7.2
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: obiyIumCtwt43Fu4nV0d
    type: GitHub
  - generic:
      secret: go4P0f0HzRJbbYbZy4VF
    type: Generic
  - type: ConfigChange
  - imageChange:
    type: ImageChange
