apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2019-11-06T08:09:47Z"
  generation: 2
  labels:
    app: mysql
  name: mysql
  namespace: archana-solipuram-ally-com-strategy
  resourceVersion: "37624005"
  selfLink: /apis/apps.openshift.io/v1/namespaces/archana-solipuram-ally-com-strategy/deploymentconfigs/mysql
  uid: cc8378fe-006c-11ea-b0f4-0a580a80009a
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: mysql
    deploymentconfig: mysql
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: mysql
        deploymentconfig: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: testdb
        - name: MYSQL_PASSWORD
          value: redhat
        - name: MYSQL_USER
          value: test
        image: registry.access.redhat.com/rhscl/mysql-57-rhel7@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - mysql
      from:
        kind: ImageStreamTag
        name: mysql:latest
        namespace: archana-solipuram-ally-com-strategy
      lastTriggeredImage: registry.access.redhat.com/rhscl/mysql-57-rhel7@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-06T08:10:07Z"
    lastUpdateTime: "2019-11-06T08:10:07Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: "2019-11-06T08:10:08Z"
    lastUpdateTime: "2019-11-06T08:10:08Z"
    message: replication controller "mysql-1" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
