apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
      volume.kubernetes.io/selected-node: ip-10-0-167-172.ec2.internal
    creationTimestamp: "2019-11-03T13:57:39Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: quotesdb-claim
    namespace: archana-solipuram-ally-com-quotes-dev
    resourceVersion: "36336311"
    selfLink: /api/v1/namespaces/archana-solipuram-ally-com-quotes-dev/persistentvolumeclaims/quotesdb-claim
    uid: e5a1f437-fe41-11e9-b0dc-02bc9323208e
  spec:
    accessModes:
    - ReadWriteOnce
    dataSource: null
    resources:
      requests:
        storage: 300Mi
    storageClassName: gp2
    volumeMode: Filesystem
    volumeName: pvc-e5a1f437-fe41-11e9-b0dc-02bc9323208e
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
