apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: "2019-11-03T14:00:52Z"
    labels:
      app: quotesapi
    name: quotesapi
    namespace: archana-solipuram-ally-com-quotes-dev
    resourceVersion: "36337423"
    selfLink: /apis/route.openshift.io/v1/namespaces/archana-solipuram-ally-com-quotes-dev/routes/quotesapi
    uid: 58b6e40d-fe42-11e9-b41a-0a580a8200fe
  spec:
    host: quotesapi-archana-solipuram-ally-com-quotes-dev.apps.ocp-na1.prod.nextcle.com
    port:
      targetPort: 8080-tcp
    subdomain: ""
    to:
      kind: Service
      name: quotesapi
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2019-11-03T14:00:52Z"
        status: "True"
        type: Admitted
      host: quotesapi-archana-solipuram-ally-com-quotes-dev.apps.ocp-na1.prod.nextcle.com
      routerCanonicalHostname: apps.ocp-na1.prod.nextcle.com
      routerName: default
      wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
